# jellyfin-media-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
spec:
  capacity:
    storage: 50Gi  # Adjust size as needed
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.2   # nfs server         
    path: /mnt/storage/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi  # Must match the PV size
