apiVersion: apps/v1
kind: Deployment
metadata:
  name: bond-nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 4 
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
