apiVersion: apps/v1
kind: Deployment
metadata:
  name: bond-mealie 
  labels:
    app: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
      - name: mealie
        image: ghcr.io/mealie-recipes/mealie:v1.3.2
        ports:
          - containerPort: 9000
            
