# jellyfin-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  type: NodePort  # Use LoadBalancer if supported
  ports:
  - port: 8096
    targetPort: 8096
    nodePort: 30000  # Optional: Specify a NodePort (default range is 30000-32767)
  selector:
    app: jellyfin
