apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-deb
  name: my-deb
spec:
  replicas: 4 
  selector:
    matchLabels:
      app: my-deb
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  
  template:

    metadata:
      labels:
        app: my-deb
    spec:
      containers:
      - image: httpd 
        name: httpd
