apiVersion: v1
kind: PersistentVolume
metadata:
  name: mealie-data-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: "/data/mealie"
